[package]
name = "gitfacts"
version = "0.1.0"
authors = ["Xiuheng <wxhbuaa@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
env_logger = "0.8.1"
clap = "3.0.0-beta.2"
git2 = "0.13"
