version: "3.3"
services:
  slicing-driver:
    environment:
      - PYTHONUNBUFFERED=1
    build: .
    container_name: facts-slicing
    # entrypoint: /bin/bash
    # stdin_open: true # docker run -i
    # tty: true        # docker run -t
    volumes:
      - datavol:/data
    # command: bash -c "
    #   python3 -m hislicing.main --prepare /data/json/name_eval.json -l info
    #   && python3 -m hislicing.main --fact /data/json/group_eval.json -l info
    #   && python3 -m run_grok -p /data/resources/file-level/output/facts -g /data/json/group_eval.json -s /data/grok-scripts/slice_ver.ql -o slice.out -l info
    #   "
    command: bash -c "
      python3 -m hislicing.main --prepare /data/json/name_one.json -l info
      && python3 -m hislicing.main --fact /data/json/group_one.json -l info
      && python3 -m run_grok -p /data/resources/file-level/output/facts -g /data/json/group_one.json -s /data/grok-scripts/slice_ver.ql -o slice.out -l info
      "
  rts-driver:
    environment:
      - PYTHONUNBUFFERED=1
    build: .
    container_name: facts-rts
    volumes:
      - datavol:/data
    command: bash -c "
      tar xf /data/defects4j/rts-repos.tar.xz -C /data/defects4j/project_repos
      && python3 -m rts.main --debug -l info --alt-config rts/config/docker.cfg -f --ensure-all-change-types
      && python3 -m rts.main --debug -l INFO --alt-config rts/config/docker.cfg -s /data/grok-scripts/rts5-imprecise.ql
      && python3 -m rts.main --debug -l INFO --alt-config rts/config/docker.cfg -v --count-method-json /data/rts-exp/results.json
      && python3 -m rts.main --debug -l INFO --alt-config rts/config/docker.cfg --percent /data/rts-exp/results.json
      "
volumes:
  datavol: {}
