# configuration
# for baseline doop
[mode]
vcs = "git"
build_system = "maven"

[input]
repo_path = "/lifting/.test/commons-net"
project_name = "" # if blank, will be basename of repo_path
rev_range = "abd6711~10..abd6711"

[exe-ctrl]
# full_jar = true
# incr_jar = true
multi_process = 4  # if number <= 0 then os.cpu_count() is used
steps_to_run = ["doop"]  # only two steps for baseline

[doop]
flavor = "orig"
doop_root = "/lifting/doop"
analysis = "1-call-site-sensitive+heap"

[doop.annotation]
sha1digits = 8

[output]
output_dir =  ".dpad"
time_suffix = true
store_metadata = true
